[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "kipoi-enformer"
version = "0.0.1"
description = "Kipoi-based variant effect prediction around the TSS using Enformer"
authors = [
    { name = "Florian HÃ¶lzlwimmer", email = "git.ich@frhoelzlwimmer.de" },
    { name = "George Tsitsiridis", email = "gtsitsiridis@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT licence" }
keywords = ["model zoo", "deep learning", "enformer", "aparent2",
    "computational biology", "bioinformatics", "genomics"]
dependencies = [
    "cyvcf2>=0.30.28",
    "numpy>=1.26.4",
    "pandas>=2.2.1",
    "pyarrow>=16.1.0",
    "pyranges>=0.0.129",
    "kipoiseq @ git+https://github.com/gtsitsiridis/kipoiseq.git@master",
    "tensorflow-hub==0.16.1",
    "tensorflow==2.16.1",
    "polars>=1.5.0",
    "scikit-learn>=1.4.1.post1",
    "lightgbm>=4.3.0",
    "zarr>=2.15.0",
    "xarray>=2024.5.0"
]
[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-xdist",
    "cython"
]
gpu = [
    "tensorflow-gpu>=2.16.1"
]